name: Deployment pipeline

on:
  push:
    branches:
      - main
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3    
      - name: Build project
        run: npm run build
      - uses: actions/upload-pages-artifact@v1 
      - uses: actions/deploy-pages@v1
